name: Post to instagram Cron Job

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    env:
      INSTAGRAM_CLIENT: ${{ secrets.INSTAGRAM_CLIENT }}
      INSTAGRAM_SECRET: ${{ secrets.INSTAGRAM_SECRET }}
      MIDJOURNEY_URL: ${{ secrets.MIDJOURNEY_URL }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        run: |
          python main.py $INSTAGRAM_CLIENT $INSTAGRAM_SECRET $MIDJOURNEY_URL
